// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using test5.Models;

namespace test5.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20171126235802_AddPhoneAndUserTypeProperties")]
    partial class AddPhoneAndUserTypeProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("test5.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("Email");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Phone");

                    b.Property<string>("State")
                        .HasMaxLength(2);

                    b.Property<string>("UserType");

                    b.Property<int>("Zip")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
